import test from 'node:test';
import assert from 'node:assert/strict';
import { createGame, TOKEN, assignToken, removeToken, actionComplete, resolveRound, startRoundResolution, resolveNextAction, drawRound, drawEnemyCard, buildBag, currentAction, continueBattle } from './game.js';

const readyGame = seed => { const game = createGame(seed); continueBattle(game); return game; };

test('fixed bag contains one token per stat point', () => { const bag = buildBag(); assert.equal(bag.length, 24); assert.equal(bag.filter(t => t === TOKEN.PHYSICAL).length, 5); assert.equal(bag.filter(t => t === TOKEN.CRITICAL).length, 5); });
test('reserve never exceeds eight tokens', () => { const game = readyGame(2); game.reserve = Array(8).fill(TOKEN.PHYSICAL); drawRound(game); assert.equal(game.reserve.length, 8); });
test('assignment, removal, and completion preserve tokens', () => { const game = readyGame(3); game.reserve = [TOKEN.PHYSICAL, TOKEN.PHYSICAL]; const action = game.actions[0]; assert.equal(assignToken(game, 0, action.id), true); assert.equal(assignToken(game, 0, action.id), true); assert.equal(actionComplete(action), true); assert.equal(game.reserve.length, 0); assert.equal(removeToken(game, action.id, 0), true); assert.equal(actionComplete(action), false); assert.equal(game.reserve.length, 1); });
test('completed player action damages enemy and evolves', () => { const game = readyGame(5); game.reserve = [TOKEN.PHYSICAL, TOKEN.PHYSICAL]; assignToken(game, 0, 'steel-strike'); assignToken(game, 0, 'steel-strike'); game.enemy.drawPile = [2]; const before = game.enemy.hp; resolveRound(game); assert.ok(game.enemy.hp < before); assert.equal(game.actions[0].evolved, true); assert.equal(currentAction(game.actions[0]).name, 'Tempered Strike'); });
test('armor absorbs enemy damage and persists into next planning round', () => { const game = readyGame(7); game.hero.armor = 5; game.enemy.drawPile = [0]; resolveRound(game); assert.equal(game.hero.hp, game.hero.maxHp); assert.equal(game.hero.armor, 1); });
test('enemy Miss reshuffles and enemy cards evolve after resolving', () => { const game = readyGame(11); assert.equal(game.enemy.cards.length, 8); game.enemy.drawPile = [7]; const miss = drawEnemyCard(game); assert.equal(miss.kind, 'miss'); assert.equal(game.enemy.drawPile.length, game.enemy.cards.length); game.enemy.drawPile = [0]; resolveRound(game); assert.equal(game.enemy.cards[0].evolved, true); });
test('lethal player action cancels enemy action later in initiative', () => { const game = readyGame(13); game.enemy.hp = 1; game.reserve = [TOKEN.PHYSICAL]; assignToken(game, 0, 'quick-strike'); game.enemy.drawPile = [0]; const hp = game.hero.hp; resolveRound(game); assert.equal(game.hero.hp, hp); assert.equal(game.phase, 'battle-transition'); });
test('round resolution advances one queued action at a time', () => { const game = readyGame(17); game.reserve = [TOKEN.PHYSICAL]; assignToken(game, 0, 'quick-strike'); game.enemy.drawPile = [0]; const enemyHp = game.enemy.hp; assert.equal(startRoundResolution(game), true); assert.equal(game.phase, 'resolving'); assert.equal(game.resolution.queue.length, 2); const result = resolveNextAction(game); assert.equal(result.name, 'Quick Strike'); assert.ok(game.enemy.hp < enemyHp); assert.equal(game.phase, 'resolving'); resolveNextAction(game); assert.equal(game.phase, 'planning'); });
test('resolution results expose applied armor and health changes', () => { const game = readyGame(19); game.hero.armor = 5; game.enemy.drawPile = [0]; startRoundResolution(game); const result = resolveNextAction(game); assert.deepEqual(result.effects, [{ target: 'hero-armor', delta: -4, label: '-4 Armor' }]); assert.equal(game.hero.hp, game.hero.maxHp); });
